import { Flashcard } from '../models/index.js'
import { generateFlashcardsWithAI } from '../services/aiService.js'
import { AppError, NotFoundError, ValidationError } from '../utils/errors.js'

const wrap = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next)

const SPACED_INTERVALS = [1, 3, 7, 14, 30]

export const getFlashcards = wrap(async (req, res) => {
  const filter = { userId: req.user._id }
  if (req.query.category) filter.category = req.query.category
  if (req.query.dueOnly === 'true') filter.nextReviewAt = { $lte: new Date() }

  const cards = await Flashcard.find(filter)
    .populate('problemId', 'title difficulty tags')
    .sort({ nextReviewAt: 1 })
    .limit(500)
  res.json({ success: true, count: cards.length, data: cards })
})

export const getDueToday = wrap(async (req, res) => {
  const cards = await Flashcard.find({
    userId: req.user._id,
    nextReviewAt: { $lte: new Date() },
  })
    .populate('problemId', 'title difficulty tags')
    .sort({ nextReviewAt: 1 })
  res.json({ success: true, count: cards.length, data: cards })
})

export const generateFlashcards = wrap(async (req, res) => {
  const { problemId, problemData, analysis } = req.body
  if (!problemData) throw new ValidationError('problemData is required')
  const result = await generateFlashcardsWithAI(problemData, analysis)

  const cards = await Flashcard.insertMany(
    result.flashcards.map((fc) => ({
      userId: req.user._id,
      problemId: problemId || null,
      front: fc.front,
      back: fc.back,
      category: fc.category || 'general',
      difficulty: problemData.difficulty,
      tags: problemData.tags || [],
      isAutoGenerated: true,
      nextReviewAt: new Date(),
    }))
  )
  res.json({ success: true, message: 'Flashcards generated', data: cards })
})

export const createFlashcard = wrap(async (req, res) => {
  const { problemId, front, back, category, difficulty, tags } = req.body
  const card = await Flashcard.create({
    userId: req.user._id,
    problemId: problemId || null,
    front,
    back,
    category: category || 'general',
    difficulty: difficulty || 'Medium',
    tags: tags || [],
    isAutoGenerated: false,
    nextReviewAt: new Date(),
  })
  res.status(201).json({ success: true, message: 'Flashcard created', data: card })
})

export const bulkCreate = wrap(async (req, res) => {
  const { cards } = req.body
  if (!Array.isArray(cards) || cards.length === 0) {
    throw new ValidationError('cards must be a non-empty array')
  }
  if (cards.length > 100) throw new ValidationError('Too many cards (max 100)')

  const docs = cards.map((c) => ({
    userId: req.user._id,
    problemId: c.problemId || null,
    front: c.front,
    back: c.back,
    category: c.category || 'general',
    difficulty: c.difficulty || 'Medium',
    tags: c.tags || [],
    isAutoGenerated: false,
    nextReviewAt: new Date(),
  }))
  const created = await Flashcard.insertMany(docs)
  res.status(201).json({ success: true, count: created.length, data: created })
})

export const updateFlashcard = wrap(async (req, res) => {
  const { id } = req.params
  const allowed = ['front', 'back', 'category', 'difficulty', 'tags', 'problemId']
  const updates = {}
  for (const k of allowed) if (req.body[k] !== undefined) updates[k] = req.body[k]

  const card = await Flashcard.findOneAndUpdate(
    { _id: id, userId: req.user._id },
    { $set: updates },
    { new: true, runValidators: true }
  )
  if (!card) throw new NotFoundError('Flashcard not found')
  res.json({ success: true, data: card })
})

export const deleteFlashcard = wrap(async (req, res) => {
  const card = await Flashcard.findOneAndDelete({ _id: req.params.id, userId: req.user._id })
  if (!card) throw new NotFoundError('Flashcard not found')
  res.json({ success: true, message: 'Flashcard deleted' })
})

export const reviewFlashcard = wrap(async (req, res) => {
  const { id } = req.params

  let quality = req.body.quality
  if (quality === undefined && typeof req.body.correct === 'boolean') {
    quality = req.body.correct ? 4 : 2
  }
  if (typeof quality !== 'number' || quality < 0 || quality > 5) {
    throw new ValidationError('Provide a quality 0-5 or a boolean `correct`')
  }

  const card = await Flashcard.findById(id)
  if (!card) throw new NotFoundError('Flashcard not found')
  if (card.userId.toString() !== req.user._id.toString()) {
    throw new AppError('Not your card', 403)
  }

  card.reviewCount = (card.reviewCount || 0) + 1
  if (quality >= 3) {
    card.correctCount = (card.correctCount || 0) + 1
    card.confidenceLevel = Math.min(SPACED_INTERVALS.length, (card.confidenceLevel || 0) + 1)
  } else {
    card.confidenceLevel = Math.max(1, (card.confidenceLevel || 1) - 1)
  }

  const idx = Math.min(card.confidenceLevel - 1, SPACED_INTERVALS.length - 1)
  const days = quality < 3 ? 1 : SPACED_INTERVALS[idx]
  card.nextReviewAt = new Date(Date.now() + days * 86_400_000)
  card.lastReviewedAt = new Date()
  await card.save()

  res.json({ success: true, message: 'Flashcard reviewed', data: card })
})

export default {
  getFlashcards,
  getDueToday,
  generateFlashcards,
  createFlashcard,
  bulkCreate,
  updateFlashcard,
  deleteFlashcard,
  reviewFlashcard,
}
