import mongoose from 'mongoose'

const flashcardSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      // Indexed via the compound indexes below; do NOT add `index: true`.
    },
    problemId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Problem',
      required: true,
    },
    front: {
      type: String,
      required: true,
    },
    back: {
      type: String,
      required: true,
    },
    category: {
      type: String,
      enum: ['pattern', 'concept', 'complexity', 'trick', 'edge_case'],
      default: 'pattern',
    },
    difficulty: {
      type: String,
      enum: ['Easy', 'Medium', 'Hard'],
      required: true,
    },
    tags: [String],
    reviewCount: {
      type: Number,
      default: 0,
    },
    correctCount: {
      type: Number,
      default: 0,
    },
    lastReviewedAt: {
      type: Date,
      default: null,
    },
    nextReviewAt: {
      type: Date,
      default: Date.now,
    },
    confidenceLevel: {
      type: Number,
      min: 1,
      max: 5,
      default: 1,
    },
    isAutoGenerated: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
)

// Indexes for spaced repetition
flashcardSchema.index({ userId: 1, nextReviewAt: 1 })
flashcardSchema.index({ userId: 1, category: 1 })

const Flashcard = mongoose.model('Flashcard', flashcardSchema)

export default Flashcard
